# -*- coding: utf-8 -*-
"""Advice Improvement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QOJqSIesE9HH8txx1vifyMGs32NKAXil
"""

"""
Food Review Advice Improvement System using DistilBERT (BERT Fine-tuning)

The program uses a DistilBERT-based model to train food review data which it uses to classify
three types of errors including order accuracy and customization errors and food quality.
The system uses the model to analyze McDonald's reviews which it enhances through
keyword-based rules before creating the final labeled dataset.

Input:
- foodreviewdata.csv (labeled training data)
- mcdonaldsfoodreview.csv (unlabeled reviews)

Output:
- mcdonalds_reviews_predicted.csv (predicted and refined labels)

"""
#############################
# Libraries and Data Setup
#############################

# Install the required data processing libraries
!pip install transformers torch pandas scikit-learn

import pandas as pd
import torch
import torch.nn as nn
import numpy as np
import io
from torch.utils.data import Dataset, DataLoader
from transformers import DistilBertTokenizer, DistilBertModel
from torch.optim import AdamW
from sklearn.preprocessing import LabelEncoder
from google.colab import files

# Check if a GPU is available to make training faster
processing_device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Upload the training and McDonald's CSV files
uploaded_files = files.upload()

def find_file(name):
    for key in uploaded_files.keys():
        if name.lower() in key.lower(): return key
    return None

# Load files using 'utf-8-sig' to preserve emojis and special characters
train_df = pd.read_csv(io.BytesIO(uploaded_files[find_file('foodreviewdata')]), encoding='utf-8-sig')
mcd_df = pd.read_csv(io.BytesIO(uploaded_files[find_file('mcdonaldsfoodreview')]), encoding='utf-8-sig')

# Fill empty cells in training data with logical defaults
for col, val in [('OrderAccuracy','Correct'), ('CustomizationError','None'), ('FoodQuality','N/A')]:
    train_df[col] = train_df[col].fillna(val)

########################
# Keyword Safety Net
########################

# Define specific keywords to override predictions for accuracy

QUALITY_KEYWORDS = {
    "Stale": ["never fresh", "not fresh", "stale", "hard", "old"],
    "Cold": ["not hot", "cold", "ice cold", "freezing"],
    "Hot": ["hot", "steaming", "piping", "freshly made"],
    "Burnt": ["burnt", "burned", "charred"],
    "Undercooked": ["pink", "raw", "undercooked"],
    "Soggy": ["soggy", "mushy", "wet"]
}

CUSTOM_KEYWORDS = {
    "None": ["no special orders", "standard order"],
    "Wrong sauce": ["sauce", "mayo", "ketchup", "mustard", "ranch"],
    "Missing ingredients": ["no cheese", "no onion", "no pickle", "without"],
    "Wrong customizations": ["asked for", "requested", "instead of", "plain"]
}

ACCURACY_KEYWORDS = {
    "Missing item": ["missing", "forgot", "didnt get", "not in the bag"],
    "Incorrect": ["wrong item", "wrong sandwich", "not what i ordered"]
}

def apply_overrides(text, current_label, rules):
    t = str(text).lower()
    for label, keywords in rules.items():
        if any(k in t for k in keywords): return label
    return current_label

# Convert text labels into numbers
order_enc = LabelEncoder().fit(train_df["OrderAccuracy"])
custom_enc = LabelEncoder().fit(train_df["CustomizationError"])
quality_enc = LabelEncoder().fit(train_df["FoodQuality"])

####################
# Model Structure
####################

# Initialize the word tokenizer
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")

class ReviewDataset(Dataset):
    def __init__(self, comments, orders=None, customs=None, qualities=None):
        self.comments = comments
        self.orders = orders
        self.customs = customs
        self.qualities = qualities

    def __len__(self): return len(self.comments)

    def __getitem__(self, i):
        tok = tokenizer(str(self.comments[i]), truncation=True, padding="max_length", max_length=64, return_tensors="pt")
        item = {"ids": tok["input_ids"].squeeze(0), "mask": tok["attention_mask"].squeeze(0)}
        if self.orders is not None:
            item.update({"o": torch.tensor(self.orders[i]), "c": torch.tensor(self.customs[i]), "q": torch.tensor(self.qualities[i])})
        return item

class FeedbackAI(nn.Module):
    def __init__(self):
        super().__init__()
        self.bert = DistilBertModel.from_pretrained("distilbert-base-uncased")
        h = self.bert.config.hidden_size
        self.o_head = nn.Linear(h, len(order_enc.classes_))
        self.c_head = nn.Linear(h, len(custom_enc.classes_))
        self.q_head = nn.Linear(h, len(quality_enc.classes_))

    def forward(self, ids, mask):
        x = self.bert(ids, attention_mask=mask).last_hidden_state[:, 0]
        return self.o_head(x), self.c_head(x), self.q_head(x)

model = FeedbackAI().to(processing_device)

##########################
# Training and Labeling
##########################

# Prepare data loaders and optimizer
loader = DataLoader(ReviewDataset(train_df["Comment"].values, order_enc.transform(train_df["OrderAccuracy"]),
                    custom_enc.transform(train_df["CustomizationError"]), quality_enc.transform(train_df["FoodQuality"])),
                    batch_size=32, shuffle=True)

optimizer = AdamW(model.parameters(), lr=2e-5)
loss_fn = nn.CrossEntropyLoss()

# Train the model on the examples
model.train()
for epoch in range(2):
    for i, b in enumerate(loader):
        optimizer.zero_grad()
        po, pc, pq = model(b["ids"].to(processing_device), b["mask"].to(processing_device))
        loss = loss_fn(po, b["o"].to(processing_device)) + loss_fn(pc, b["c"].to(processing_device)) + loss_fn(pq, b["q"].to(processing_device))
        loss.backward(); optimizer.step()
        # Print batch progress to help keep track
        if i % 10 == 0: print(f"Epoch {epoch+1}, Batch {i} processed")

# Process and label the McDonald's reviews
model.eval()
raw_comments = mcd_df["Comment"].fillna("").astype(str).values
inf_loader = DataLoader(ReviewDataset(raw_comments), batch_size=32)

out_o, out_c, out_q = [], [], []
with torch.no_grad():
    for b in inf_loader:
        po, pc, pq = model(b["ids"].to(processing_device), b["mask"].to(processing_device))
        out_o.extend(order_enc.inverse_transform(po.argmax(1).cpu().numpy()))
        out_c.extend(custom_enc.inverse_transform(pc.argmax(1).cpu().numpy()))
        out_q.extend(quality_enc.inverse_transform(pq.argmax(1).cpu().numpy()))

# Apply overrides and save the final file
final_o, final_c, final_q = [], [], []
for i, txt in enumerate(raw_comments):
    final_o.append(apply_overrides(txt, out_o[i], ACCURACY_KEYWORDS))
    final_c.append(apply_overrides(txt, out_c[i], CUSTOM_KEYWORDS))
    final_q.append(apply_overrides(txt, out_q[i], QUALITY_KEYWORDS))

mcd_df["OrderAccuracy"], mcd_df["CustomizationError"], mcd_df["FoodQuality"] = final_o, final_c, final_q
mcd_df.to_csv("mcdonalds_reviews_predicted.csv", index=False, encoding='utf-8-sig')
files.download("mcdonalds_reviews_predicted.csv")





